In [3]:
import numpy as np

In [5]:
a = np.array([3,2,1])
a

array([3, 2, 1])

In [6]:
c = range(10000)
%timeit [i**3 for i in c]

3.42 ms ± 148 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
c_numpy = np.arange(10000)
%timeit c_numpy**3

28.2 µs ± 1.48 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [9]:
l1 = range(10000)
l2 = [i**2 for i in range(10000)]

In [10]:
%timeit list(map(lambda x, y: x*y, l1, l2))

1.26 ms ± 58.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
a1 = np.array(l1)
b1 = np.array(l2)

In [12]:
%timeit a1*b1

5.83 µs ± 213 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
a1 * a1

array([       0,        1,        4, ..., 99940009, 99960004, 99980001])

In [14]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [16]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [20]:
np.full((3,3),2.2, dtype= np.int)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [21]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [22]:
v = np.array([1,2,3])
np.tile(v,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [23]:
a.itemsize

8

In [24]:
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [25]:
a = np.arange(1,10)

In [26]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [27]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [28]:
a.std()

2.581988897471611

In [29]:
a = np.arange(1,10).reshape(3,3)

In [30]:
np.linalg.det(a)

0.0

In [31]:
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [32]:
a
b = a.T

In [33]:
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
np.dot(a,b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [35]:
a = np.array([1,1,0], dtype = bool)
b = np.array([1,0,1], dtype = bool)

In [36]:
np.logical_or(a,b)

array([ True,  True,  True])

In [37]:
a = np.array([[1,2],[3,4]])

In [38]:
a.sum(axis=0)

array([4, 6])

In [39]:
a.argmax()

3

In [40]:
a.shape(/
    )

SyntaxError: invalid syntax (<ipython-input-40-9ef22c63bcf2>, line 1)

In [41]:
a.shape()

TypeError: 'tuple' object is not callable

In [42]:
a.shape

(2, 2)

In [43]:
a[:,np.newaxis].shape

(2, 1, 2)

In [44]:
np.sort(a)

array([[1, 2],
       [3, 4]])

In [45]:
np.argsort(a)

array([[0, 1],
       [0, 1]])