In [2]:
#Importing numpy
import numpy as np

In [8]:
#initializing arrays
arr = np.array([1,2,3,4])
arr_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr_3d)
print("dimension",arr_3d.ndim)
print("Shape",arr_3d.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension 3
Shape (1, 3, 3)


In [9]:
#slicing in 3d and changing a row
arr_3d[0,0,:] = [0]
print(arr_3d)

[[[0 0 0]
  [4 5 6]
  [7 8 9]]]


In [10]:
#changing a column
arr_3d[0,:,1] = [0]
arr_3d

array([[[0, 0, 0],
        [4, 0, 6],
        [7, 0, 9]]])

In [11]:
np.arange(1,25,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [12]:
a = np.array([2,2,2,2])
b = np.array([3,3,3,3])
a*b

array([6, 6, 6, 6])

In [13]:
arr1 = np.full((3,3),0)
arr1
arr2 = np.full((3,3,3),1)
arr2.shape

(3, 3, 3)

In [14]:
one = np.ones((3,3))
one.ndim
z = np.zeros(arr1.shape)
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
a = np.array([1,2,3,4,5],dtype = 'int64')
b = np.array([1.0,2.0,3.0,4.0,5.0], dtype = 'float')
a == b
5*a


array([ 5, 10, 15, 20, 25], dtype=int64)

In [20]:
np.random.random([2,2])


array([[0.16368387, 0.02365108],
       [0.50853715, 0.10942129]])

In [32]:
aray = np.array([[1,2,3],[4,5,6]])
print(aray)
print(aray.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [35]:
a>1

array([False,  True,  True,  True,  True])

In [37]:
a.sum()

15

In [54]:
m = np.array([[0,9,8,7],[6,5,4,3]])
n = np.array([[6,5,4,3],[0,9,8,7]])
np.vstack((m,n))

array([[0, 9, 8, 7],
       [6, 5, 4, 3],
       [6, 5, 4, 3],
       [0, 9, 8, 7]])

In [64]:
print(np.sin(a))
print(m.T)
print(m)
m_copy = m
np.shares_memory(m,m_copy)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[[0 6]
 [9 5]
 [8 4]
 [7 3]]
[[0 9 8 7]
 [6 5 4 3]]


True

In [67]:
n_copy = n.copy
n_copy is n
np.shares_memory(n,n_copy)

False