<h1 align="center">NumPy Practise</h1>
<br>
<br>

#### Ajay Vardhan Reddy

#### CSSOC - ML

In [1]:
import numpy as np

# Basics

In [2]:
a=np.array([1,2,3],dtype='int32') #create an array
print(a)

[1 2 3]


In [3]:
b=np.array([[1.0,2.0,8.0],[6.0,5.0,4.0]])
print(b)

[[1. 2. 8.]
 [6. 5. 4.]]


In [4]:
b.ndim

2

In [5]:
b.shape

(2, 3)

In [6]:
b.dtype

dtype('float64')

In [7]:
a.itemsize

# 'a' is a container.It has 3 items in it. As each item is an integer variable. 
# Hence, the size of each item is 4.

4

In [8]:
'''
a = [1,2,3]
item_size = 4
size_of_a = 3
a.nbytes = item_size * size_of_a
a.nbytes = 4 * 3 =>12
'''

a.nbytes
# return total_size of a in bytes


12

### Accessing/Changing specific elements, rows, columns, etc:

In [9]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [10]:
arr[1,5] #accessinga specific element from arr

12

In [11]:
arr[0,:] #slicing

array([1, 2, 3, 4, 5, 6])

In [12]:
# Getting a little more fancy [startindex:endindex:stepsize]
arr[0,2:-1:2]

array([3, 5])

In [13]:
# change value at a specific column and row
arr[0,4]=20
arr

array([[ 1,  2,  3,  4, 20,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [14]:
# change values of one specific column for all rows
arr[:,2]=[1,2]
arr

array([[ 1,  2,  1,  4, 20,  6],
       [ 7,  8,  2, 10, 11, 12]])

In [15]:
a = np.array([1,2,3,4,5,6,7,8,9,-1,-2,-3])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, -1, -2, -3])

In [16]:
#printing the values of array 'a' which are greater than 2
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
#printing the values which are negative
a[a<0]

array([-1, -2, -3])

### 3D arrays:

In [18]:
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
arr_3d[0,0,0]

# 1st parameter-> row
# 2nd parameter-> subrows of row
# 3rd parameter-> column

1

### Initializing Different Types of Arrays

In [20]:
# All 0s Matrix
# return a new array of given shape and type, filled with zeros.
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# all 1s matrix
np.ones((4,3,3),dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [22]:
#Return a new array of given shape and type, filled with `fill_value`.
np.full((3,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [23]:
# Return a full array with the same shape and type as a given array.
np.full_like(arr,5)  # arr is given array \

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [24]:
# create an array with random integers
np.random.randint(1,high=5,size=(3,3))

#syntax:  np.random.randint(low=start_value,high=end_value,size(can be a number or shape))

array([[1, 2, 2],
       [2, 3, 3],
       [1, 1, 2]])

In [25]:
# Create an array with decimal Number
np.random.rand(3,3)

array([[0.28144435, 0.65740105, 0.47198671],
       [0.24991277, 0.84983882, 0.38565261],
       [0.34276758, 0.47354441, 0.86094142]])

In [26]:
# Identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
# Repeat an array

ar = np.array([[1,2,3]])
repeat_array = np.repeat(ar,3,axis=0)
repeat_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [28]:
a = np.array([1,2,3])
copy_array=a
print('copy_array: ',copy_array)

#update copy_array

copy_array[0]=100

# Now,check array 'a'
a
# a also changes when you change in copy_array, so instead of copying directly use copy() function.

copy_array:  [1 2 3]


array([100,   2,   3])

In [29]:
a = np.array([1,2,3])
copy_array=a.copy()
print('copy_array: ',copy_array)
copy_array[0]=100

# Now,check array 'a'
a
# you can see when we update copy_array , there is no change in array 'a'

copy_array:  [1 2 3]


array([1, 2, 3])

# Mathematics:

In [30]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [31]:
a+2

array([3, 4, 5, 6])

In [32]:
a-2

array([-1,  0,  1,  2])

In [33]:
a*2

array([2, 4, 6, 8])

In [34]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [35]:
b = np.array([1,0,1,0]) # make sure both arrays are of equal size
a + b

array([2, 2, 4, 4])

In [36]:
# Trignometric functions

np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [37]:
np.cos(0)

1.0

In [38]:
arr1 = np.array([1,1,0],dtype=bool)
arr2 = np.array([1,0,0], dtype = bool)

In [39]:
np.logical_or(arr1,arr2)

array([ True,  True, False])

In [40]:
np.logical_and(arr1,arr2)

array([ True, False, False])

# linear Algebra

### 1) Multiply two matrix:

In [41]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)
np.matmul(a,b)
# make sure that columns of matrix 'a' are equal to rows of 'b'

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

### 2) Determinant:


In [42]:
# find det for identity matrix

iden_mat=np.identity(3)
print(iden_mat)

np.linalg.det(iden_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

### 3) Transpose:

In [43]:
arr = np.array([[1,2,3],[4,5,6]])
print("arr:")
print(arr,'\n')
print("Transpose of arr: ")
print(arr.T)

arr:
[[1 2 3]
 [4 5 6]] 

Transpose of arr: 
[[1 4]
 [2 5]
 [3 6]]


# statistics:

In [44]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.min(stats)

1

In [46]:
np.max(stats,axis=0)

array([4, 5, 6])

In [47]:
np.max(stats,axis=1)

array([3, 6])

In [48]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganizing Arrays:

In [49]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((4,2))
after
# while you reshape array, try using reverse of shape of array

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [50]:
# Vertically stacking vectors
# placing one array on other
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2]))

print('\n')

print(np.vstack([v1,v2,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]]


[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [51]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# load data from txt file

In [52]:
txt_file = np.genfromtxt('data.txt',delimiter=',')
txt_file

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [53]:
#change data type of txt_file

txt_file=txt_file.astype('int32')
print(txt_file)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# Boolean Masking and Advanced Indexing

In [54]:
(txt_file>50) & (txt_file<100) 

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [55]:
~((txt_file>50) & (txt_file<100) )

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

## arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

In [56]:
x_val = np.arange(0,4.5,0.5)
x_val

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])